package com.synergyforce.rashel.sundail.extras;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * @author Estique Ahmed Rashel
 */

public class HistoryModel extends RealmObject {

    @PrimaryKey
    private int _id;

    private String _endTime;
    private String _note;
    private String _startTime;

    //getters and setters method generated by IDE

    public String get_endTime() {
        return _endTime;
    }

    public void set_endTime(String _endTime) {
        this._endTime = _endTime;
    }

    public int get_id() {
        return _id;
    }

    public void set_id(int _id) {
        this._id = _id;
    }

    public String get_startTime() {
        return _startTime;
    }

    public void set_startTime(String _startTime) {
        this._startTime = _startTime;
    }

    public String get_note() {
        return _note;
    }

    public void set_note(String _note) {
        this._note = _note;
    }


}
